var GAME_LEVELS = [
  ["                                                                                       ",
   "                             o         o                        o o                    ",
   "                                                                                       ",
   "                   xxxxxxxx!xx!xxxxxx!xx!xxxxx    xxxxx        xxxxx                   ",
   "              o           x!!!!x    x!!!!x            x                                ",
   "                          x!!!!x    x!!!!x     xx     xxxx                             ",
   "              xx          xxxxxx    xxxxxx               x                             ",
   "                                             x!!!!x      xxxx                          ",
   "  xx                            o o           xxxx          x                          ",
   "  x      xx                                                 xxxx                       ",
   "  x                            xxxxx                                                   ",
   "  x                                                                           xxxxxxx  ",
   "  x           xx                                                     xx           xxx  ",
   "  x  @                                                    p                         x  ",
   "  xxxxxxxxx      xxxxxxxxxxx                             ppp        o o             x  ",
   "          xxxxxxxx         x                              p                         x  ",
   "                           x                           xxxxxxx       xxxxx          x  ",
   "                           xxxxxxxxxxxxxx!!!!!!!xxxxxxx       xxxxxxx     xxxxxxxxxxx  ",
   "                                        x!!!!!!!x                                      ",
   "                                        x!!!!!!!x                                      ",
   "                                        x!!!!!!!x                                      ",
   "                                        xxxxxxxxx                                      ",
   "                                                                                       ",
   "                                                                                       "],
  ["   x!!!!!!!!!x                                                                                               x!x  ",
   "   xxxxxvxxxxx                                                                                               x!x  ",
   "          x                                                                      oo                          x!x  ",
   "          x                                                                                                  x!x  ",
   "          x                            o                                                          o   o   o  x!x  ",
   "     @    x                           xxx                                                                   xx!x  ",
   "    xxx   x                                                                                   xxxxxxxxxxxxxxx!!x  ",
   "      x   x                                                                                     !!!!!!!!!!!!!!xx  ",
   "      x   x                                                                              xxxxxxxxxxxxxxxxxxxxxx   ",
   "      x  xx              o  o     xxxxxxxxxxxxx                                          |                        ",
   "      x   x                       x            x                                                                  ",
   "      x   x                    y  x            xxxxxxx                           xxx     |   xxx                  ",
   "!!!!!!xx  x           xxx    xxx x             x     x                           x x         x x                  ",
   "!!!!!!x   x         xxx          x             x     x                             x     |   x                    ",
   "!!!!!!x   x        xx  x!!!!!!!!!x             x     x                             xx        x                    ",
   "xxxxxxx  xx       xx   x!!!!!!!!!x             xx    x       p                     x         x                    ",
   "      x          xx    xxxxxxxxxxx       o     x     x      ppp          x         x         x                    ",
   "      x        xxxxxxx                         x             p           x         x         x                    ",
   "              xx     xx                        x           xxxxxx        x   xxxxxxxxx       x                    ",
   "             xx       xx                       x                         x   x               x                    ",
   "            xx         x                       x==                       x   x               x                    ",
   "    xxxx               x                xxxx   x                         xxxxx   xxx         x                    ",
   "    x x                x       xx o xx         x     xxx      xxxxx        o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!xx   xx       =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx    xxxxxxxxxxxxxxx xx  o o   x                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx                      x        x                    ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx                       xxxxxxxxxx                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx                                                      ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx                                                       ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                        "],
  ["                                                                             v                                ",
   "                                                                               v                 v            ",
   "                                                                                       v                      ",
   "                                                                                   v                          ",
   "                                                                                     v                        ",
   "                                        o                                                  v                  ",
   "                                                                                 v                            ",
   "                                        x                                                          v          ",
   "                                        x                                                    v                ",
   "                                        x                                                      v              ",
   "                                        x                   x          x                 v           v        ",
   "                                       xxx                  x          x                                      ",
   "                                       x x                  x          x                                      ",
   "                                       x x                  x          x                                      ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x                               v      ",
   "                                      x   x                 x          x                                      ",
   "                                      x   x       t         xxxxxxxxxxxx                                      ",
   "                                      x   xxttttttx   x      x              xx                           v    ",
   "                                      x   xxxxxxxxx   xxxxxxxx                                                ",
   "                                      x   x           x                                                       ",
   "                                      x   x           x                                                       ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x                                                       ",
   "                                      x   x           x                                                       ",
   "                                      x   x    = = = =x     o                       o                         ",
   "                                      x   xx          x                                                       ",
   "                              o   o   x   x           x     x                      xxx                        ",
   "                                      x   x           x              x                                        ",
   "                             xxxxxx  xxx xxx     o o  x!!!!!!!!!!!!!!x                                        ",
   "                             x    x  x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx=         =xx                                                                  ",
   "  xxx                        xx     x     x                                                              xxx  ",
   "  x x                        xx    xxx    x                                                              x x  ",
   "  x                      x   xx    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                          xx           x                              x                                 x  ",
   "  x                          xxx          x            xxxxxx            x                                 x  ",
   "  x                          xx           x            |    |            x                                 x  ",
   "  x                          xx    o o    x                              x                xxx              x  ",
   "  x                          xxx=        =x            |    |            xx               x x              x  ",
   "  x                          xx    xxx    x                              x                x x              x  ",
   "  x                          xxxxxxxxxxxxxx  x oo x    |    |    x oo    xxx              x x         o o  x  ",
   "  x      @             y     xx           x!!x    xy   |    |    x    xxx  xx             x x              x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxx xxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                            ",
   "                   ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                ",
   "                                                                                                            ",
   "                                                                                                            ",
   "                                                                                                            ",
   "                                                                                                            ",
   "                     ooooo   o   o   ooooo   ooooo   ooooo   ooooo   ooooo                                  ",
   "                     o       o   o   o       o       o       o       o                                    x ",
   " x                   ooooo   o   o   o       o       ooo     ooooo   ooooo                                x ",
   " x                       o   o   o   o       o       o           o       o                                x ",
   " x                   ooooo   ooooo   ooooo   ooooo   ooooo   ooooo   ooooo                                x ",
   " x                                                                                                        x ",
   " x  @                                                                                                     x ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
